version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        uid: 1000
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./apache_log:/var/log/apache2
    ports:
      - 8080:80
